#%RAML 1.0 Library

types:

  AnalysisBase:
    additionalProperties: false
    properties:
      displayName: string
      description: string
      studyId: string
      studyVersion: string
      apiVersion: string
      isPublic: boolean

  AnalysisSummary:
    additionalProperties: false
    type: AnalysisBase
    properties:
      analysisId: string
      creationTime: string
      modificationTime: string
      numFilters: integer
      numComputations: integer
      numVisualizations: integer

  AnalysisSummaryWithUser:
    additionalProperties: false
    type: AnalysisSummary
    properties:
      userId: number
      userName: string
      userOrganization: string

  AnalysisListPostRequest:
    additionalProperties: false
    type: AnalysisBase
    properties:
      descriptor: AnalysisDescriptor

  AnalysisListPostResponse:
    additionalProperties: false
    properties:
      analysisId: string

  AnalysisListPatchRequest:
    additionalProperties: false
    properties:
      analysisIdsToDelete?: string[]
      inheritOwnershipFrom?: integer

  AnalysisDetail:
    additionalProperties: false
    type: AnalysisSummary
    properties:
      descriptor: AnalysisDescriptor

  SingleAnalysisPatchRequest:
    additionalProperties: false
    properties:
      displayName?: string
      description?: string
      descriptor?: AnalysisDescriptor
      isPublic?: boolean

  DataTableConfig:
    additionalProperties: false
    properties:
      variables: VariableSpec[]
      sorting: SortSpecEntry[]

  DataTableConfigSet:
    properties:
      //: # not sure of entity name allowed regex
        type: DataTableConfig

  AnalysisDescriptor:
    additionalProperties: false
    properties:
      subset:
        properties:
          descriptor: object[]
          uiSettings?: object
      computations: Computation[]
      starredVariables: VariableSpec[]
      dataTableConfig: DataTableConfigSet
      derivedVariables: DerivedVariable[]

  Computation:
    additionalProperties: false
    properties:
      computationId: string
      displayName: string
      descriptor: object
      visualizations: Visualization[]

  Visualization:
    additionalProperties: false
    properties:
      visualizationId: string
      displayName: string
      descriptor: object

